# Customize this file and rename to `.travis.yml` for implementation.

branches:
  only:
  - master
  - staging
  - dev

language: bash

services:
  - docker

before_install:
  - sudo pip install --upgrade pip
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin 

install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build --no-cache -t uvarc/vce-app:latest . || exit 1;
    docker push uvarc/vce-app:latest || exit 1;
    aws sqs send-message --queue-url 'https://queue.amazonaws.com/474683445819/dcos-refresh' --message-body 'jablonski/vce-app' || exit 1;
    fi
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then
    docker build --no-cache -t uvarc/vce-app:dev . || exit 1;
    docker push uvarc/vce-app:dev || exit 1;
    fi

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - mst3k@virginia.edu
